import { SITE } from "./site";

export const SEO = {
  defaultTitle: "ONTO DIGITAL",

  titleTemplate: "%s | ONTO DIGITAL",

  description:
    "Premium Digital Agency specializing in Web Development, UI/UX, Branding and Web Applications.",

  keywords: [
    "Web Development",
    "UI UX",
    "Next.js",
    "React",
    "Digital Agency",
  ],

  // Shared Open Graph / Twitter image, generated by app/opengraph-image.tsx.
  // Referenced explicitly in every route's metadata because Next.js's
  // opengraph-image file convention does not cascade into nested segments
  // that define their own `openGraph` object, which every page here does
  // (see https://github.com/vercel/next.js/discussions/50353).
  ogImage: {
    url: "/opengraph-image",
    width: 1200,
    height: 630,
    alt: `${SITE.name} — ${SITE.tagline}`,
  },
};